front:
  build: ./
  ports:
    - "80:80"
  volumes:
    - "./src:/data/src"
    - "./conf:/etc/nginx/conf.d"
  command: ["nginx", "-g", "daemon off;"]
  networks:
      app_net:
        ipv4_address: 172.17.0.2
        ipv6_address: 2001:3984:3989::10

networks:
  tars_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.17.0.0/24
        gateway: 172.17.0.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
